name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Ember
        run: pnpx ember-cli@5 new fresh-app --package-manager=pnpm
      - name: Update test-helpers package
        run: cd fresh-app && pnpm add @ember/test-helpers@4.0.5
      - name: Remove the welcome page package and template content
        run: |
          cd fresh-app
          pnpm rm ember-welcome-page
          head -n 4 ./app/templates/application.hbs > temp.hbs && mv temp.hbs ./app/templates/application.hbs
      - name: Add a favicon
        run: touch fresh-app/public/favicon.ico
      - name: Install puppeteer
        run: pnpm install
      - name: Serve and dump with puppeteer
        run: |
          cd fresh-app
          pnpm ember serve --environment=production & echo $! > ../server.pid
          pnpx wait-on http://localhost:4200
          node ../dump-browser.js || { echo -e "\033[31mConsole errors detected\033[0m"; exit 1; }
      - name: clean up
        run: |
          kill $(cat server.pid) || true
          rm server.pid
