name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Ember
        run: pnpx ember-cli@5 new fresh-app --package-manager=pnpm
      - name: Run Tests with a production build
        run: cd fresh-app && pnpm ember test --environment=production
